# Generated by Django 4.1.4 on 2022-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bode',
            new_name='content',
        ),
    ]
