# Generated by Django 4.1.4 on 2022-12-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='is_favorite',
        ),
    ]
